# Generated by Django 3.2.5 on 2021-08-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='status',
        ),
    ]
