# Generated by Django 3.2.5 on 2021-08-26 19:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='border_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
