# Generated by Django 3.2.5 on 2021-08-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210818_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
