# Generated by Django 3.2.5 on 2021-08-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tables.status'),
        ),
    ]
