# Generated by Django 3.2.5 on 2021-08-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
