# Generated by Django 3.2.5 on 2021-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_historicaltable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('in_use', 'In User'), ('ordered', 'Ordered')], default='ready', max_length=100),
        ),
        migrations.DeleteModel(
            name='HistoricalTable',
        ),
    ]
