# Generated by Django 3.2.5 on 2021-08-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20210831_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('ordered', 'Ordered')], default='ready', max_length=100),
        ),
    ]
