# Generated by Django 3.2.5 on 2021-08-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
