# Generated by Django 3.2.7 on 2021-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_item_variation_options', to='products.VariationOption'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total_price_record',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_price_record',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
