# Generated by Django 3.2.7 on 2021-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0003_auto_20210918_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variation_options',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_variation_options',
            field=models.ManyToManyField(related_name='order_item_variation_options', to='products.VariationOption'),
        ),
    ]
