# Generated by Django 3.2.5 on 2021-08-18 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productvariationoption_variation_option'),
        ('tables', '0002_alter_table_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='tables.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_option', to='products.productvariationoption'),
        ),
    ]
