# Generated by Django 3.2.5 on 2021-08-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('serving', 'Serving'), ('paid', 'Paid'), ('canceled', 'Canceled')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
