# Generated by Django 3.2.5 on 2021-08-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210830_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
