# Generated by Django 3.2.5 on 2021-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210830_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paied_by',
            new_name='paid_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('serving', 'Serving'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=100),
        ),
    ]
