# Generated by Django 3.2.7 on 2021-09-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Iten', 'verbose_name_plural': 'Order Itens'},
        ),
    ]
