# Generated by Django 3.2.7 on 2021-09-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitemrecord_orderrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order'),
        ),
        migrations.DeleteModel(
            name='OrderItemRecord',
        ),
        migrations.DeleteModel(
            name='OrderRecord',
        ),
    ]
