# Generated by Django 3.2.7 on 2021-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20210915_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_price_record',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
