# Generated by Django 3.2.7 on 2021-09-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_order_total_price_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_price_record',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
