# Generated by Django 3.2.5 on 2021-08-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
