# Generated by Django 3.2.5 on 2021-09-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='variation',
        ),
        migrations.AddField(
            model_name='extra',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='products.variation'),
        ),
        migrations.RemoveField(
            model_name='extravariationoption',
            name='variation_option',
        ),
        migrations.AddField(
            model_name='extravariationoption',
            name='variation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_option', to='products.variationoption'),
        ),
    ]
