# Generated by Django 3.2.5 on 2021-09-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210919_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extravariationoption',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_variation_options', to='products.extra'),
        ),
    ]
