# Generated by Django 3.2.5 on 2021-08-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210814_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varitation',
            new_name='Variation',
        ),
        migrations.RenameField(
            model_name='productvariationoption',
            old_name='varitation_option',
            new_name='variation_option',
        ),
    ]
