# Generated by Django 3.2.5 on 2021-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_extravariationoption_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='variation',
        ),
        migrations.AddField(
            model_name='extra',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ExtraVariationOption',
        ),
    ]
