# Generated by Django 3.2.5 on 2021-08-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210815_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariationoption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
