# Generated by Django 3.2.5 on 2021-08-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariationoption_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(to='products.Label'),
        ),
        migrations.DeleteModel(
            name='ProductLabel',
        ),
    ]
