# Generated by Django 3.2.5 on 2021-08-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210816_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariationoption',
            name='product_variation',
        ),
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(to='products.Variation'),
        ),
        migrations.AlterField(
            model_name='productvariationoption',
            name='variation_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.variationoption'),
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
