# Generated by Django 3.2.5 on 2021-08-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210816_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(related_name='label', to='products.Label'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='products.status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(related_name='variation', to='products.Variation'),
        ),
        migrations.AlterField(
            model_name='productvariationoption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_option', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariationoption',
            name='variation_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variation_option', to='products.variationoption'),
        ),
    ]
