# Generated by Django 3.2.5 on 2021-08-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210818_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariationoption',
            name='variation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_option', to='products.variationoption'),
        ),
    ]
