# Generated by Django 3.2.5 on 2021-08-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210818_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='dark_theme_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='label',
            name='light_theme_color',
            field=models.CharField(default='#023458', max_length=7),
        ),
    ]
