# Generated by Django 3.2.5 on 2021-08-19 08:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210819_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='dark_theme_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='label',
            name='light_theme_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
