# Generated by Django 3.2.5 on 2021-08-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210819_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='dark_theme_color',
            new_name='background_color',
        ),
        migrations.RemoveField(
            model_name='label',
            name='light_theme_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
