# Generated by Django 3.2.7 on 2021-09-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210831_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='productvariationoption',
            name='variation_option',
        ),
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='labels', to='products.Label'),
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(related_name='variations', to='products.Variation'),
        ),
        migrations.AddField(
            model_name='productvariationoption',
            name='variation_options',
            field=models.ManyToManyField(related_name='variation_options', to='products.VariationOption'),
        ),
    ]
