# Generated by Django 3.2.7 on 2021-09-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210915_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='variation',
            field=models.ManyToManyField(related_name='variation', to='products.Variation'),
        ),
        migrations.CreateModel(
            name='ExtraVariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_variation_option', to='products.extra')),
                ('variation_option', models.ManyToManyField(related_name='variation_option', to='products.VariationOption')),
            ],
        ),
    ]
