# Generated by Django 3.2.7 on 2021-09-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210915_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariationoption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_options', to='products.product'),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='products.variation'),
        ),
    ]
